### ISSUE TITLE
RangeFilters do not work on 64-bit integers

### ISSUE THREAD

**Issue by duk-37** [manticoresoftware/manticoresearch-net#2]
[This line](https://github.com/manticoresoftware/manticoresearch-net/blob/d0c115418e69be1124b5974013834f007e56c869/src/ManticoreSearch/Api/SearchApi.cs#L570) causes an exception to be thrown if the value passed to a `RangeFilterValue` does not fit in a 32-bit integer.

```cs
using ManticoreSearch.Api;
using ManticoreSearch.Model;

public static class Program
{
    public static void Main(string[] args)
    {
        var searchAPi = new SearchApi();
        var filters = new BoolFilter(must:
        [
            new RangeFilter("id", gt: new RangeFilterValue(111111111111L))
        ]);

        var searchReq = new SearchRequest("messages")
        {
            AttrFilter = filters
        };

        searchAPi.Search(searchReq);
    }
}
```

**Comment by Nick-S-2018** [comment]
Hi,
Sorry for delay with the response. This issue will be fixed in the next release coming in a few days.

**Comment by Nick-S-2018** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1807

**Comment by Nick-S-2018** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/2269

**Comment by Nick-S-2018** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch-net/commit/d88c065f895bccb89f9a6c1ddc27b00f6f097d9a
